# -*- coding: utf-8 -*-
"""
Created on Tue May  7 21:26:53 2024

@author: C266584
"""

import random

#list of all participants
givers = ['Lane','Erin','Jimmy','Maria','Jon','Jamie','Mike','Linnea']
receivers = ['Lane','Erin','Jimmy','Maria','Jon','Jamie','Mike','Linnea']

#dictionary on who can't be paired
couples = {'Lane':'Erin','Jimmy':'Maria','Jon':'Jamie','Mike':'Linnea','Erin':'Lane','Maria':'Jimmy','Jamie':'Jon','Linnea':'Mike'}

#person can only be paired once


#randomly select participant, then pair, and go through list until everyone has been paired
i = 1
p = len(givers)
#randomly loop and select givers
while i < p:
    g = random.choice(givers) #randomly select from available givers, print and pause
    input(
"""...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...

"""
+g+"""! 

It is your turn to make a selection. 

When you are are ready, please press enter.""")
    #break
    n=0
    while n<1: #do a while loop in order to check for eligible matches
        r = random.choice(receivers)
        #print("round 1")
        if couples[g] != r and g != r: #check if match is same person or a couple
            print("""Successful match!
                  """)
            n=1
        else:
            print("""Error in match, running again ...
                  """)
    input (r+""" is your match. Congratulations. 

Press enter to see who is next
""")
    givers.remove(g) #remove giver from givers list before starting over
    receivers.remove(r) #remove receiver from receivers list before starting over
    i = i+1
    #break
    
#randomly assign a given that is not equal to dictionary assignment
#remove giver/given from list


